# Generated by Django 4.1.3 on 2025-10-19 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='referee_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
