# Generated by Django 4.1.3 on 2025-10-22 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_profile_referee_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='has_badge',
            field=models.BooleanField(default=False),
        ),
    ]
