# Generated by Django 4.1.3 on 2025-10-16 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_profile_referral_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='referral_code',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='referral_count',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='referred_by',
        ),
    ]
